let data = [
  {
    "cedula": 30716524,
    "nombre": "ALAÑA FIGUEROA, JOSE ROBERTO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,25",
    "subTotalParcial1": "6,25"
  },
  {
    "cedula": 31258709,
    "nombre": "ALCON LUQUEZ, WILLIAN ADRIEL",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "1,00",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 30601545,
    "nombre": "ALVARADO COLMENAREZ, EDUARD ALEXANDER",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "0,60",
    "subTotalParcial1": "1,60"
  },
  {
    "cedula": 30396056,
    "nombre": "ALVAREZ ATACHO, GUSTAVO ALFONSO",
    "condicion": 1,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,60",
    "microM2": "1,00",
    "subTotalParcial1": "2,60"
  },
  {
    "cedula": 31047787,
    "nombre": "ARRIECHI TUA, YULIANNYS JOSE",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "0,00",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 26945225,
    "nombre": "AVENDAÑO RODRIGUEZ, YOSWER ANTONIO",
    "condicion": 2,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 30105122,
    "nombre": "BARRAEZ JIMENEZ, ALEXIS MANUEL",
    "condicion": 2,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "0,60",
    "microM2": "0,25",
    "subTotalParcial1": "1,85"
  },
  {
    "cedula": 32023320,
    "nombre": "BARRETO MARTINEZ, ALEX JOSE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "n/p",
    "subTotalParcial1": "4,00"
  },
  {
    "cedula": 28382638,
    "nombre": "BENAVENTE ALEJO, STEPHANIE MARGARETH",
    "condicion": 3,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31271788,
    "nombre": "CAMACARO RODRIGUEZ, JOETH LUIS",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 25137790,
    "nombre": "CAMEJO REYES, ASAEL JOAS",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "0,50",
    "subTotalParcial1": "1,50"
  },
  {
    "cedula": 30868201,
    "nombre": "CAMPOS YEPEZ, MICHELLE CAROLINA",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 17034323,
    "nombre": "CARRILLO MORALES, LILIBETH LILIANA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,40",
    "microM2": "1,75",
    "subTotalParcial1": "5,15"
  },
  {
    "cedula": 20351023,
    "nombre": "CATARI MONTILLA, JOHAN ANDRES",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "2,60",
    "microM2": "2,60",
    "subTotalParcial1": "6,20"
  },
  {
    "cedula": 30004665,
    "nombre": "CHAVEZ PATIÑO, MOISES ENRIQUE",
    "condicion": 2,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30916875,
    "nombre": "CHAVEZ PEREIRA, LUIS DAVID",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31118017,
    "nombre": "CURE RIVERO, ANGEL DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "1,10",
    "microM2": "n/p",
    "subTotalParcial1": "2,10"
  },
  {
    "cedula": 27586641,
    "nombre": "DELGADO LOVATON, SOFIA NAZARETH",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "0,30",
    "microM2": "1,40",
    "subTotalParcial1": "2,70"
  },
  {
    "cedula": 31366805,
    "nombre": "DIAZ HUANG, JHONN RAIKAR",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31972026,
    "nombre": "DOMINGUEZ MENDOZA, DIANA VALESKA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 30553694,
    "nombre": "ESCALONA COLMENARES, DANIELA ALEJANDRA",
    "condicion": 1,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "1,00",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 31973382,
    "nombre": "ESCALONA MORALES, JESUA JAHZEEL",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 30845134,
    "nombre": "ESCALONA SANGRONIS, LUIS ANGEL",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,25",
    "subTotalParcial1": "6,25"
  },
  {
    "cedula": 31041717,
    "nombre": "ESCALONA SILVA, JOSE DAVID",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30479767,
    "nombre": "FAJARDO DE LA VEGA, ALEJANDRO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,00",
    "microM2": "2,00",
    "subTotalParcial1": "5,00"
  },
  {
    "cedula": 25992343,
    "nombre": "FALCON RAMOS, ABRAHAN JOSE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 31066347,
    "nombre": "FERRER SILVA, MELANY ANDREINA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "0,50",
    "subTotalParcial1": "0,50"
  },
  {
    "cedula": 31026165,
    "nombre": "FIGUEROA PERDOMO, DANIELA ALEJANDRA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "1,00",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 30844907,
    "nombre": "FLORES LEON, CARLOS ALBERTO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "1,00",
    "microM2": "n/p",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 30014426,
    "nombre": "FREITEZ PEREZ, FRANYELIZ CAROLINA",
    "condicion": 3,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "0,30",
    "subTotalParcial1": "1,30"
  },
  {
    "cedula": 30754077,
    "nombre": "FUENTES VALERA, MANUEL ALEJANDRO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "1,20",
    "subTotalParcial1": "1,20"
  },
  {
    "cedula": 31099867,
    "nombre": "GARCIA GUTIERREZ, ANA KARINA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "1,00",
    "microM2": "n/p",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 30042305,
    "nombre": "GARCIA LOPEZ, DARIAN FABIOLA",
    "condicion": 1,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,60",
    "microM2": "n/p",
    "subTotalParcial1": "3,60"
  },
  {
    "cedula": 28113561,
    "nombre": "GARCIA PIRES, JUAN ANDRES",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,60",
    "microM2": "1,75",
    "subTotalParcial1": "5,35"
  },
  {
    "cedula": 29944538,
    "nombre": "GHANIM SILVA, SAID ALEJANDRO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "1,50",
    "microM2": "2,50",
    "subTotalParcial1": "5,00"
  },
  {
    "cedula": 31368020,
    "nombre": "GIL PICHARDO, ESTEFANY PAOLA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31766071,
    "nombre": "GIMENEZ SALAS, JOSE LEONARDO",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31025997,
    "nombre": "GONZALEZ SANCHEZ, RICARDO ANDRES",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 29851080,
    "nombre": "GUERRERO CRESPO, ALAN GABRIEL",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "0,50",
    "microM2": "n/p",
    "subTotalParcial1": "1,50"
  },
  {
    "cedula": 28566175,
    "nombre": "GUTIERREZ GIMENEZ, GENESIS DEL CARMEN",
    "condicion": 1,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31195152,
    "nombre": "HERNANDEZ GUERRA, NELSON ANTONIO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "0,00",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 30325234,
    "nombre": "HERNANDEZ MENA, FERNANDO JESUS",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,60",
    "microM2": "n/p",
    "subTotalParcial1": "3,60"
  },
  {
    "cedula": 29693793,
    "nombre": "HORYEN FUENTES, SOPHIA VICTORIA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31221654,
    "nombre": "LINARES GONZALEZ, LUIS ALFONSO",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "0,00",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 31492754,
    "nombre": "LINAREZ GOMEZ, YESSICA CAROLINA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "n/p",
    "subTotalParcial1": "4,00"
  },
  {
    "cedula": 29915697,
    "nombre": "LOBO RAMIREZ, CARLOS ANDRES",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30916802,
    "nombre": "LOPEZ MENDOZA, AXEL DAVID",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30894990,
    "nombre": "LUCENA LUCENA, NIXON ALEXANDER",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "0,00",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 28204478,
    "nombre": "LUNA BARRIOS, ORIANA VALENTINA",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "0,50",
    "subTotalParcial1": "1,50"
  },
  {
    "cedula": 11427399,
    "nombre": "MARDINI CHAMI, NELLY",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31089011,
    "nombre": "MARQUEZ ARIAS, DANIELA SOFIA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 30353228,
    "nombre": "MARTINEZ SUAREZ, DEIVERSON ISAAC",
    "condicion": 1,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31026972,
    "nombre": "MARTINEZ VASQUEZ, ABRAHAN JOSE",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30454226,
    "nombre": "MEDINA ALVARADO, CARLOS JOSE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31401788,
    "nombre": "MEDINA APOSTOL, KEIBER JESUS",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30803408,
    "nombre": "MEDINA BELIZAMONT, PAOLA VALENTINA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "0,00",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 27828367,
    "nombre": "MENDOZA UGEL, MARIA VALENTINA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "0,60",
    "subTotalParcial1": "1,60"
  },
  {
    "cedula": 28204836,
    "nombre": "MONTES TAMBO, ALBERIT MAURICIO",
    "condicion": 2,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30417042,
    "nombre": "MONTILLA MONTES, JESUS GABRIEL",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,60",
    "microM2": "0,00",
    "subTotalParcial1": "1,60"
  },
  {
    "cedula": 31533895,
    "nombre": "MORALES TARAZONA, JEIKER DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,00",
    "microM2": "2,00",
    "subTotalParcial1": "5,00"
  },
  {
    "cedula": 16956628,
    "nombre": "MORENO VEGA, LUIS ENRIQUE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,40",
    "microM2": "1,75",
    "subTotalParcial1": "5,15"
  },
  {
    "cedula": 29896078,
    "nombre": "MORILLO RODRIGUEZ, GEOVANNY JESUS",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31535238,
    "nombre": "NAVAS VASQUEZ, JHADIEL DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 31771381,
    "nombre": "OLIVERO RIVERO, VALERY CAROLINA",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "0,00",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 31147057,
    "nombre": "OLIVEROS GIL, SAMUEL JOSUE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "1,00",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 26831389,
    "nombre": "OLLARVES RAMOS, JORGE LUIS",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "2,60",
    "microM2": "2,60",
    "subTotalParcial1": "6,20"
  },
  {
    "cedula": 31195093,
    "nombre": "ORTEGANO HERNANDEZ, ADRIAN ALEJANDRO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 28021112,
    "nombre": "OSAL MENDOZA, JOSMERY PAOLA",
    "condicion": 1,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "1,50",
    "subTotalParcial1": "2,50"
  },
  {
    "cedula": 30480247,
    "nombre": "OVALLES GODOY, ARIANA ELENA",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "2,00",
    "microM2": "1,70",
    "subTotalParcial1": "4,70"
  },
  {
    "cedula": 16277237,
    "nombre": "PACHECO MARTINEZ, ALEXANDRA CAROLINA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31271481,
    "nombre": "PACHECO SANCHEZ, EDWUAR JHESSUA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "2,70",
    "subTotalParcial1": "2,70"
  },
  {
    "cedula": 30560241,
    "nombre": "PALACIOS BRICENO, FRANCISCO JAVIER",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 31025923,
    "nombre": "PARADAS MENDOZA, CARLOS DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "0,00",
    "subTotalParcial1": "4,00"
  },
  {
    "cedula": 29517195,
    "nombre": "PEÑA CASAMAYOR, MARIA VICTORIA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 29517375,
    "nombre": "PERAZA COLMENAREZ, VALERIA ALEXANDRA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 29517861,
    "nombre": "PERAZZO JAIMES, MARCO ANTONIO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,60",
    "microM2": "0,25",
    "subTotalParcial1": "1,85"
  },
  {
    "cedula": 30995733,
    "nombre": "PEREZ AMADO, RICARDO DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 30072358,
    "nombre": "PEREZ CORTEZ, ESTEFANI GABRIELA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30803393,
    "nombre": "PEREZ MUNDARAIN, NICKOLL GISELLE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 29795841,
    "nombre": "PEREZ PIÑERO, CRISTIAN JOSE",
    "condicion": 3,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "1,00",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 29831953,
    "nombre": "PERNALETE TORCATEZ, OSWMAR DANIEL",
    "condicion": 1,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "1,10",
    "microM2": "0,00",
    "subTotalParcial1": "2,10"
  },
  {
    "cedula": 31077148,
    "nombre": "PINEDA ESCALONA, WILEIDY COROMOTO",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30895054,
    "nombre": "RANGEL VASQUEZ, KAREN MARIANA",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,90",
    "subTotalParcial1": "6,90"
  },
  {
    "cedula": 29805195,
    "nombre": "REIS PEREZ, MANUEL ALEJANDRO",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 26990816,
    "nombre": "RIVAS FRIAS, HUMBERTO GREGORIO",
    "condicion": 3,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30753633,
    "nombre": "RIVERO TORO, EMILSON GREGORIO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "1,10",
    "microM2": "1,20",
    "subTotalParcial1": "3,30"
  },
  {
    "cedula": 31077168,
    "nombre": "RODRIGUEZ ALVARADO, MAICKOL JESUS",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 29795856,
    "nombre": "RODRIGUEZ RODRIGUEZ, BRAIAN JOSUE",
    "condicion": 1,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "1,00",
    "microM2": "1,00",
    "subTotalParcial1": "3,00"
  },
  {
    "cedula": 28113260,
    "nombre": "ROMERO BENITEZ, CAREN GERALDINE",
    "condicion": 2,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,00",
    "microM2": "1,50",
    "subTotalParcial1": "2,50"
  },
  {
    "cedula": 31401043,
    "nombre": "ROMERO SUAREZ, CARLOS DANIEL",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 32034829,
    "nombre": "SALAS OCANDO, LIANA GABRIELA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 29976433,
    "nombre": "SANCHEZ PEREZ, OLIVER JOSE",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 27760864,
    "nombre": "SEQUERA PARRA, JARBI ALEXANDER",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,60",
    "microM2": "1,75",
    "subTotalParcial1": "5,35"
  },
  {
    "cedula": 27397444,
    "nombre": "SERRANO ARTEAGA, LUIS SEGUNDO",
    "condicion": 3,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31195126,
    "nombre": "SERRANO HERNANDEZ, OMAR DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "1,00"
  },
  {
    "cedula": 29778391,
    "nombre": "SIERRALTA ESCALONA, REBECA SARAHI",
    "condicion": 3,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 28493285,
    "nombre": "SIVIRA SIVIRA, JOSE ENRIQUE",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "n/p",
    "microM2": "1,00",
    "subTotalParcial1": "2,00"
  },
  {
    "cedula": 30266566,
    "nombre": "SOTO PAEZ, TOMAS DAVID",
    "condicion": 0,
    "materia": 3154,
    "seccion": 3,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "2,70",
    "subTotalParcial1": "2,70"
  },
  {
    "cedula": 30528931,
    "nombre": "SUAREZ DAZA, JOSE GABRIEL",
    "condicion": 2,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 27212680,
    "nombre": "SUAREZ MORALES, YELIMAR ANGELICA",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 27844065,
    "nombre": "TENIAS CASTELLANOS, OSCAR ALBERTO",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "2,90",
    "microM2": "2,80",
    "subTotalParcial1": "6,70"
  },
  {
    "cedula": 30454491,
    "nombre": "TORIN PARTIDAS, MOISES ABRAHAM",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 31066236,
    "nombre": "TORO CASTRO, YOSGER ENRIQUE",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "3,00",
    "microM2": "2,50",
    "subTotalParcial1": "6,50"
  },
  {
    "cedula": 30657710,
    "nombre": "TOVAR PANZA, ISAIAS OCTAVIO",
    "condicion": 0,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,60",
    "microM2": "0,00",
    "subTotalParcial1": "1,60"
  },
  {
    "cedula": 27828899,
    "nombre": "VASQUEZ LEON, CARLOS GERARDO",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "1,00",
    "microM1": "1,00",
    "microM2": "1,00",
    "subTotalParcial1": "3,00"
  },
  {
    "cedula": 25433440,
    "nombre": "VILORIA NOGUERA, GUSTAVO ADOLFO",
    "condicion": 0,
    "materia": "C4",
    "seccion": 1,
    "profesor": "Giovanni Torrealba",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 30255498,
    "nombre": "YEPEZ FIGUEIRA, RAY ANGEL",
    "condicion": 0,
    "materia": 3154,
    "seccion": 2,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "2,95",
    "microM2": "2,90",
    "subTotalParcial1": "6,85"
  },
  {
    "cedula": 28204969,
    "nombre": "ZAMBRANO ROSALES, EMMANUEL JOSE",
    "condicion": 2,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "n/p",
    "microM1": "n/p",
    "microM2": "n/p",
    "subTotalParcial1": "0,00"
  },
  {
    "cedula": 28475269,
    "nombre": "ZARAZA MENDIA, MARIANGELA JOSE",
    "condicion": 3,
    "materia": 3154,
    "seccion": 1,
    "profesor": "Olga Palma",
    "tarea1": "1,00",
    "microM1": "0,60",
    "microM2": "0,50",
    "subTotalParcial1": "2,10"
  }
];

export default data;
